# Keeps the local Vite preview synchronized with the GitHub development branch.
# Run this in a separate VS Code terminal while "npm run dev" runs in another one.
$ErrorActionPreference = 'Stop'

$ExpectedBranch = 'feature/shotlist-equipment-lens-dropdowns'
$RemoteRef = "origin/$ExpectedBranch"
$PollSeconds = 15

Set-Location -LiteralPath $PSScriptRoot

$currentBranch = (git branch --show-current).Trim()
if ($LASTEXITCODE -ne 0) {
    throw 'Could not read the current Git branch.'
}
if ($currentBranch -ne $ExpectedBranch) {
    Write-Host "Current branch: $currentBranch" -ForegroundColor Yellow
    Write-Host "Switch to '$ExpectedBranch' before starting the local sync." -ForegroundColor Yellow
    exit 1
}

Write-Host "CINEBLOCK local auto-sync is running for '$ExpectedBranch'." -ForegroundColor Green
Write-Host "Checking GitHub every $PollSeconds seconds. Vite will refresh the browser after source files update."
Write-Host 'Press Ctrl+C in this terminal to stop auto-sync.'
Write-Host ''

while ($true) {
    try {
        # Never overwrite uncommitted source edits.
        $dirtyLines = @(git status --porcelain --untracked-files=all)
        if ($LASTEXITCODE -ne 0) {
            Write-Warning 'Could not check Git status. Retrying shortly.'
            Start-Sleep -Seconds $PollSeconds
            continue
        }

        if ($dirtyLines.Count -gt 0) {
            $dirtyPaths = @($dirtyLines | ForEach-Object { $_.Substring(3).Trim().Trim('"') })
            $nonDistPaths = @($dirtyPaths | Where-Object { $_ -notmatch '^dist/' })

            # dist/ is generated by Vite; discard its build-only changes, but never source edits.
            if ($nonDistPaths.Count -eq 0) {
                git restore -- dist
                if ($LASTEXITCODE -ne 0) {
                    Write-Warning 'Could not reset generated dist/ files; pausing sync.'
                    Start-Sleep -Seconds $PollSeconds
                    continue
                }
            } else {
                Write-Warning 'Auto-sync paused because the working tree has local changes.'
                $dirtyLines | ForEach-Object { Write-Host "  $_" }
                Write-Host 'Commit or stash your edits, then restart sync-local.ps1.'
                break
            }
        }

        git fetch --quiet origin
        if ($LASTEXITCODE -ne 0) {
            Write-Warning 'Git fetch failed. Will retry.'
            Start-Sleep -Seconds $PollSeconds
            continue
        }

        $localSha = (git rev-parse HEAD).Trim()
        if ($LASTEXITCODE -ne 0) {
            Write-Warning 'Could not read local commit. Stopping sync.'
            break
        }
        $remoteSha = (git rev-parse $RemoteRef).Trim()
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "Could not read $RemoteRef. Stopping sync."
            break
        }

        if ($localSha -ne $remoteSha) {
            git merge-base --is-ancestor HEAD $RemoteRef
            if ($LASTEXITCODE -ne 0) {
                Write-Warning 'The local branch and GitHub branch have diverged. No automatic merge was made.'
                Write-Host 'Stop sync and reconcile the branches manually before restarting.'
                break
            }

            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] New GitHub changes found. Updating local files..."
            git merge --ff-only --quiet $RemoteRef
            if ($LASTEXITCODE -ne 0) {
                Write-Warning 'Fast-forward update failed. No forced changes were made.'
                break
            }
            Write-Host "[$(Get-Date -Format 'HH:mm:ss')] Local files updated. Vite should refresh the open preview." -ForegroundColor Green
        }
    } catch {
        Write-Warning $_.Exception.Message
    }

    Start-Sleep -Seconds $PollSeconds
}
